### ISSUE TITLE
Audio glitches when too many notes are played at once

### ISSUE THREAD

**Issue by BillyDM** [andersforsgren/synja#1]
The audio starts glitching when too many MIDI notes are played at once. I can only get the glitchy sound to stop by closing the plugin.

Also for some reason, when I load the plugin in Bitwig, the same glitch happens as soon as I play just one MIDI note.

Cool project btw, I'm excited to see where this goes! :)

OS: Arch Linux
Hosts tried: Bitwig, Ardour

**Comment by andersforsgren** [comment]
Can't repro the issue with too many notes, but the glitch in Bitwig was probably because it was not zeroing the output buffer + the plugin was (incorrectly) using 2in/2out so basically feeds back on itself when the DAW isn't clearing the buffers. 

I now clear the buffers in generate_audio and set the plugin to use 0in/2out as it should. Behaves ok in Bitwig 3.x on windows for me. If you can test it again that would be much appreciated. No point chasing this bug if the above change has already fixed it :)

Interesting it's if it works (almost) out of the box on Linux, considering I never even gave it a try. Did you just cargo build and grab the resulding lib? Would that work on MacOS as well?

Re: plugin needing unloading:  
I know there are also still some places when there are denormals causing the plugin to choke. Haven't found exactly where it is but some combinations of parameters seems to trip it up. Not sure if there is any way of cheating with denormals in Rust, but I should try to find those places regardless. Suspect some overflow or division by zero somewhere, and that could get trapped in the filter forever. Would probably be fine to just clamp or sanitize somewhere to avoid them getting stuck in the filter.

**Comment by BillyDM** [comment]
Yes, it seems to have fixed the issue! I also can no longer trigger the glitch with too many notes, so it must have been unrelated.

> Interesting it's if it works (almost) out of the box on Linux, considering I never even gave it a try. Did you just cargo build and grab the resulding lib? Would that work on MacOS as well

Yes, I just ran `cargo +nightly build --release` and put the lib in the `~/.vst` folder. Both `baseview` and `egui` are highly cross platform.

MacOS is more tricky, because it requires you to bundle the lib. That is something that `nih-plug` handles for you by the way. But if you don't want to switch to `nih-plug`, there are also these scripts you can use: <https://github.com/DGriffin91/egui_baseview_test_vst2/tree/main/scripts>.

**Comment by andersforsgren** [comment]
Thanks. nih-plug conversion is ongoing!
